import { gql } from "@apollo/client";
import { parse } from "graphql";

import { actionLogShowVersionDialogFragment } from "../actionLogShowVersionDialog/ActionLogShowVersionDialog";

export const actionLogsGridFragment = gql`
    fragment ActionLogsGrid on ActionLog {
        id
        entityId
        type
        createdAt
        snapshot
        user {
            id
            name
        }
        previousVersion {
            snapshot
        }
        ...ActionLogShowVersionDialog
    }
    ${actionLogShowVersionDialogFragment}
`;

/**
 * Keys of `TQuery` whose value is a `PaginatedActionLogs` — i.e. the top-level
 * `<entity>ActionLogs` queries generated by `ActionLogsModule.forFeature()`.
 * Falls back to `string` when no generic is supplied.
 */
export type ActionLogQueryName<TQuery> = string extends keyof TQuery
    ? string
    : {
          [K in keyof TQuery]: NonNullable<TQuery[K]> extends { __typename?: "PaginatedActionLogs" } ? K : never;
      }[keyof TQuery] &
          string;

export function buildActionLogsQuery(queryName: string) {
    const operationName = queryName[0].toUpperCase() + queryName.slice(1);
    const fragmentBody = actionLogsGridFragment.loc?.source.body ?? "";
    return parse(`
        query ${operationName}($scope: JSONObject!, $offset: Int!, $limit: Int!, $filter: ActionLogFilter, $sort: [ActionLogSort!]) {
            ${queryName}(scope: $scope, offset: $offset, limit: $limit, filter: $filter, sort: $sort) {
                nodes {
                    ...ActionLogsGrid
                }
                totalCount
            }
        }
        ${fragmentBody}
    `);
}
